#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
独游翻译器 · 翻译资产体检 (Asset Health Check)
================================================
**只读**扫描 XUnity 翻译资产 (_AutoGeneratedTranslations.txt), 输出四类问题计数:

  1. 完全重复原文      —— 同一 original 出现多次
  2. 归一化重复原文    —— 仅大小写/首尾空白/内部连续空白差异
  3. 空译文            —— original 非空但 translation 为空(未翻译)
  4. 译文与原文相同    —— 疑似未翻译 / 误回填

**本脚本不写盘、不修改任何文件。** 语义是"体检"而非"清理"——
清理请在 GUI 翻译管理器里点「清理重复」(可见差异、可回滚 .bak)。

退出码: 0 = 全部正常; 1 = 检出问题(可挂 CI)。

用法:
    python check_assets.py [资产文件路径]
    python check_assets.py --dir <游戏根目录>        # 自动定位资产
    python check_assets.py --json                     # 机器可读输出
    python check_assets.py --max-sample 20            # 每类最多列 20 条样例
"""

import argparse
import json as _json
import os
import re
import sys
# --- UTF-8 输出引导 ---------------------------------------------------------
# Windows 上 Python 的 stdout 默认跟随系统代码页（CI runner 是 cp1252，
# 简体中文机器常是 cp936）。脚本里中文 print 一旦遇到无法映射的编码就会抛
# UnicodeEncodeError 直接崩。这里在入口处强制 stdout/stderr 走 UTF-8。
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(encoding='utf-8', errors='replace')
    except Exception:
        pass

# 归一化: 折叠所有连续空白 → 单空格, 去首尾, 小写
_WS_RE = re.compile(r'\s+')


def normalize(s):
    return _WS_RE.sub(' ', (s or '')).strip().lower()


def translation_file_path(game_dir):
    """定位 XUnity 翻译资产 (与 GUI 同规则)。"""
    for sub in ('BepInEx/Translation/zh/Text', 'BepInEx/Translation/zh-CN/Text'):
        p = os.path.join(game_dir, sub.replace('/', os.sep),
                         '_AutoGeneratedTranslations.txt')
        if os.path.isfile(p):
            return p
    # 兜底: 一层目录搜索
    base = os.path.join(game_dir, 'BepInEx', 'Translation')
    if os.path.isdir(base):
        for lang in os.listdir(base):
            p = os.path.join(base, lang, 'Text', '_AutoGeneratedTranslations.txt')
            if os.path.isfile(p):
                return p
    return None


def load_entries(path):
    """读资产, 返回 [(original, translation)]。与 GUI 的解析规则一致。"""
    with open(path, 'rb') as f:
        raw = f.read()
    text = raw.decode('utf-8-sig', errors='replace')
    out = []
    for line in text.split('\n'):
        line = line.rstrip('\r')
        if line == '':
            continue
        if '=' in line:
            o, t = line.split('=', 1)
        else:
            o, t = line, ''
        out.append((o.rstrip('\r'), t.rstrip('\r')))
    return out, raw.startswith(b'\xef\xbb\xbf')


def check(path, max_sample=10):
    """执行体检, 返回结果 dict。"""
    entries, bom = load_entries(path)
    n = len(entries)

    # 1. 完全重复
    by_orig = {}
    for i, (o, t) in enumerate(entries):
        by_orig.setdefault(o, []).append(i)
    dup_exact = {o: idx for o, idx in by_orig.items() if len(idx) > 1}

    # 2. 归一化重复(排除已计入完全重复的)
    by_norm = {}
    for i, (o, t) in enumerate(entries):
        by_norm.setdefault(normalize(o), []).append((i, o))
    dup_norm = {}
    for k, lst in by_norm.items():
        if len(lst) < 2:
            continue
        if len({o for _, o in lst}) > 1:      # 归一化相同但原文不同 → 变体
            dup_norm[k] = lst

    # 3. 空译文 / 4. 译文==原文
    empty = [(i, e[0]) for i, e in enumerate(entries) if not e[1].strip()]
    same = [(i, e[0]) for i, e in enumerate(entries)
            if e[1].strip() and e[0].strip() and e[1] == e[0]]

    problems = len(dup_exact) + len(dup_norm) + len(empty) + len(same)
    return {
        'file': os.path.abspath(path),
        'bytes': os.path.getsize(path),
        'bom': bom,
        'total': n,
        'dup_exact_groups': len(dup_exact),
        'dup_exact_rows': sum(len(v) - 1 for v in dup_exact.values()),
        'dup_norm_groups': len(dup_norm),
        'dup_norm_rows': sum(len(v) - 1 for v in dup_norm.values()),
        'empty_translation': len(empty),
        'same_as_source': len(same),
        'problems': problems,
        'samples': {
            'dup_exact': sorted(dup_exact)[:max_sample],
            'dup_norm': ['%r vs %r' % (a, b) for k, lst in
                         list(dup_norm.items())[:max_sample]
                         for a, b in [(lst[0][1], lst[1][1])]],
            'empty': [o for _, o in empty[:max_sample]],
            'same': [o for _, o in same[:max_sample]],
        },
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description='独游翻译器 · 翻译资产体检(只读)')
    ap.add_argument('asset', nargs='?', help='资产文件路径')
    ap.add_argument('--dir', dest='game_dir', help='游戏根目录(自动定位资产)')
    ap.add_argument('--json', action='store_true', help='JSON 输出')
    ap.add_argument('--max-sample', type=int, default=10, help='每类样例上限')
    args = ap.parse_args(argv)

    path = args.asset
    if not path and args.game_dir:
        path = translation_file_path(args.game_dir)
        if not path:
            print('[体检] 在 %s 下未找到 _AutoGeneratedTranslations.txt' % args.game_dir)
            return 1
    if not path:
        print('[体检] 请给出资产文件路径或 --dir <游戏根目录>')
        return 1
    if not os.path.isfile(path):
        print('[体检] 文件不存在: %s' % path)
        return 1

    r = check(path, max_sample=args.max_sample)
    if args.json:
        print(_json.dumps(r, ensure_ascii=False, indent=2))
        return 1 if r['problems'] else 0

    print('=' * 64)
    print(' 翻译资产体检报告 (只读)')
    print('=' * 64)
    print(' 文件   : %s' % r['file'])
    print(' 体积   : %d 字节  |  BOM: %s' % (r['bytes'], r['bom']))
    print(' 总条目 : %d' % r['total'])
    print('-' * 64)
    print(' 1) 完全重复原文      : %d 组 (%d 多余行)'
          % (r['dup_exact_groups'], r['dup_exact_rows']))
    print(' 2) 归一化重复原文    : %d 组 (%d 多余行)'
          % (r['dup_norm_groups'], r['dup_norm_rows']))
    print(' 3) 空译文(未翻译)    : %d 条' % r['empty_translation'])
    print(' 4) 译文与原文相同    : %d 条' % r['same_as_source'])
    print('-' * 64)
    for key, label in (('dup_exact', '完全重复'), ('dup_norm', '归一化变体'),
                       ('empty', '空译文'), ('same', '译文==原文')):
        smp = r['samples'].get(key) or []
        if smp:
            print(' [%s] 样例:' % label)
            for s in smp:
                print('   - %s' % s)
    print('=' * 64)
    if r['problems']:
        print(' 结论: 检出 %d 项待关注(如需清理请在 GUI 点「清理重复」,' % r['problems'])
        print('       本脚本只读、不修改任何文件)。')
        return 1
    print(' 结论: 未检出问题。')
    return 0


if __name__ == '__main__':
    sys.exit(main())
