# -*- coding: utf-8 -*-
"""RPG Maker MV/MZ 引擎桥接（GUI 侧）。

v3.27（2026-10-07）：解决「RPGMaker 引擎的游戏提取不出 0 条」。

实测背景（Zombie's Retreat 2 v1.1.0）：
  * 数据**完全没加密** —— 259 个 .json，246 个 Map*.json，
    文件头 `5b 0a 6e 75 6c 6c` = `[\\nnull\\n{`，标准明文 JSON。
  * I 盘 `cli/engines/rpgmaker.py` 实跑 **0.4 秒提取 3,690 条**，
    质量良好（对白完整、key 可回写）。
  * **但 GUI 提取路径写死了 Unity**（find_asset_files + scan_and_collect），
    完全不分支 → 扫描到 0 条。

本模块职责：
  1. `detect(game_dir)`   —— 是不是 RPG Maker MV/MZ（看 www/data 或 data + MapInfos.json）
  2. `extract(game_dir)`  —— 返回 `[(key, source), ...]`，供 GUI 入库
  3. `extract_generic(game_dir)` —— 引擎不可用时的**兜底**：
     直接遍历 data/*.json，用启发式挑出像文本的字符串。宁可多收，
     也不让用户看到「扫描到 0 条」。

⚠️ **红线（v3.27）**：提取只**读**data/*.json，绝不回写。红线同 H 组护栏。

v3.29（2026-10-08）：**红线已由老板明确授权放开**——新增 apply 回写能力。
  起因：GUI 把 RPG Maker 的译文写到了 `<game_root>/_AutoGeneratedTranslations.txt`
  （那是 XUnity/Unity 的约定），而 RPG Maker MV/MZ **根本不读这个文件**，文本
  硬编码在 `www/data/*.json` 里 → 用户「保存了译文但游戏仍显示英文」。
  授权范围：**仅 RPG Maker 引擎**，且必须先全量备份原 json（`backup()`），
  并提供 `restore()` 一键还原。Unity 链路维持现状（保存即运行时生效）。
"""
from __future__ import annotations

import json
import os
import re
import shutil
import time

__all__ = ['detect', 'extract', 'extract_generic', 'find_data_dir',
           'apply', 'backup', 'restore', 'list_backups']

# RPG Maker 数据库里值得提取的字段（与引擎 rpgmaker.py 的 RPG_DB_FIELDS 对齐）
_DB_FILES = [
    'CommonEvents.json', 'Actors.json', 'Items.json', 'Weapons.json',
    'Armors.json', 'Skills.json', 'States.json', 'Enemies.json',
    'Troops.json', 'Classes.json', 'MapInfos.json', 'System.json',
]

# System.json 里是开关/变量名，不是玩家可见文本，但仍是可翻译项。
# 实测占 709 条（19%），保留但排在后面。

_MAP_RE = re.compile(r'^Map\d+\.json$')

# ---- 通用兜底的启发式 ----------------------------------------------------
# JSON 里哪些字符串像「玩家会看到的文本」：
#  · 长度 >= 2
#  · 不含控制字符
#  · 至少有一个字母
#  · 不是纯数字/纯符号/纯空白
#  · 排除颜色代码 `\c[3]`
_CTRL_RE = re.compile(r'[\x00-\x08\x0b\x0c\x0e-\x1f]')
_COLOR_CODE_RE = re.compile(r'^\\c\[?\d*\]?$')
_KEYLIKE_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')   # Actors.json#obj1-name 这类键
_NUMERIC_RE = re.compile(r'^[\d\s.,:%\-*/+()]*$')

# ---- 噪声黑名单（v3.27 实测 69,471 条全量遍历后归纳）--------------------
# 事件脚本里大量**开发者注释**与**内部命令**，不是玩家可见文本。
# 实测样本：
#   '** SET CLAW POSITION **'     ← 开发者注释
#   'AnimatedPicture 7 Speed 8'   ← 内部命令参数
#   'HC_Zombies2B'                ← 图集文件名（无空格，靠下划线判据拦）
#   'Thunder5'                    ← 音效文件名
#   '3MerOlivSex1a[4x4]'          ← 贴图图集名
_NOTE_WRAP_RE = re.compile(r'^[<>*_#\s]')
_SNAKE_UPPER_RE = re.compile(r'^[A-Za-z]*[A-Z][A-Za-z]*(_[A-Za-z0-9]+)+$')  # HC_Zombies2B
_CAMEL_NUM_RE = re.compile(r'^[A-Za-z]+\d+$')           # Thunder5
_ALL_CAPS_RE = re.compile(r'^[A-Z0-9 _]+$')             # SET CLAW POSITION
_VARNAME_RE = re.compile(r'^[A-Za-z_][A-Za-z0-9_]*$')     # 变量名 / 图集名
# camelCase 标识符：Spriteset2 / myVar / someField
_CAMEL_RE = re.compile(r'^[a-z]+[A-Z]')
# RPG Maker 控制码：`\!` `\.` `\p` `\l` `\v` `\n` `\^` `\$` `\>` `\<` `\|`
_CTRLCODE_RE = re.compile(r'\\[.!pLv n^$><|]')
# 字体标记 `<Coffee Junkie>` 是**说话人名字**，要保留；但 `\n<\n[2]>` 是换行+色码，是噪声
_LEADING_NL_CODE_RE = re.compile(r'^(\\n)+\s*<\s*\\n\s*\[\d+\]\s*')
# ---- JS 代码 / 脚本调用（v3.27 第二轮实测追加）---------------------------
#   'Galv.PROJ.dir(7,4,10,7,\'BulletMotorLZ\',0,\'c(196)'  ← 子弹脚本
#   '$gameSelfSwitches.setValue([m, e, \'D\'], false);'   ← JS 赋值
#   'Galv.BattleM.animate(...)'                          ← 战斗插件
# 判据：含JS 特征 —— `$` 变量 / `Xxx.Yyy(` 调用 / `function` / `;` 收尾 / `===`
_JS_CALL_RE = re.compile(r'\b[A-Za-z_][A-Za-z0-9_]*\.[A-Za-z_][A-Za-z0-9_]*\s*\(')
_JS_VAR_RE = re.compile(r'^\$[A-Za-z_]')
_JS_KEYWORD_RE = re.compile(
    r'\b(function|var|let|const|return|if|else|for|while|switch|case|break|'
    r'continue|new|typeof|instanceof|this|null|undefined|true|false)\b')
# ---- 带数字的图集/角色贴图名（v3.27 第三轮实测追加，残留 3,907 条）--------
#   '1MC1' '7HP_10' '1Aunt1' '1Jenny' '3MeredithShop1x[4x4]'
#   —— 事件里 image.char / image.name 字段都是图集名，不是文本。
#   判据：**无空格 + 含数字 + 不含逗号句号** —— 玩家文本几乎总是有空格和标点。
_SPRITE_NUM_RE = re.compile(r'^(?=.*\d)[A-Za-z0-9_\[\]x]+$')
# `[4x4]` 这种图集尺寸标记
_ATLAS_DIM_RE = re.compile(r'\[\d+x\d+\]$')
# 纯小写 + 可选结尾句点：**音效文件名**（实测 `city.` / `Bells` / `Door1` 等）。
# ⚠️ 只拦**带结尾句点**的（`city.` / `door.`）——音效文件名几乎都带句点，
#    而合法英文文本很少以「小写单词+句点」结尾（那通常是省略号残片，
#    由is_truncated_fragment 那一层管）。
#    裸小写单词（`ok` / `no` / `yes` / `Bells` / `Door1`）**一律放行**，
#    它们可能是道具名/事件名，误伤代价比漏掉几个音效高。
_SFX_DOT_RE = re.compile(r'^[a-z]{2,20}\.$')


def find_data_dir(game_dir):
    """定位 RPG Maker 的数据目录。返回路径或 None。

    标准布局：
      <root>/www/data        (MV/MZ)
      <root>/data            (直接包一层的情况)
    必须含 MapInfos.json 才认（避免误认普通 data 目录）。
    """
    if not game_dir or not os.path.isdir(game_dir):
        return None
    cands = [
        os.path.join(game_dir, 'www', 'data'),
        os.path.join(game_dir, 'data'),
    ]
    for c in cands:
        if os.path.isfile(os.path.join(c, 'MapInfos.json')):
            return c
    # 兜底：向下找两层
    for root, dirs, files in os.walk(game_dir):
        dirs[:] = [d for d in dirs if not d.startswith('.')]
        if 'MapInfos.json' in files:
            return root
        if root[len(game_dir):].count(os.sep) >= 3:
            dirs[:] = []
    return None


def detect(game_dir):
    """是否是 RPG Maker MV/MZ。返回 (是与否, 数据目录 或 None, 引擎名)。"""
    d = find_data_dir(game_dir)
    if not d:
        return False, None, None
    # 区分 MV / MZ：MZ 有 class 目录和 js/rmmz_*.js；MV 有 js/rpg_*.js
    js = os.path.join(os.path.dirname(d), 'js')
    mz = False
    if os.path.isdir(js):
        try:
            names = os.listdir(js)
        except Exception:
            names = []
        mz = any(n.startswith('rmmz_') for n in names)
    # 字体目录也可参考：MV 是 gamefont， MZ 是 mzfont
    fonts = os.path.join(os.path.dirname(d), 'fonts')
    if os.path.isdir(fonts):
        try:
            fn = os.listdir(fonts)
        except Exception:
            fn = []
        if any('mzfont' in n.lower() for n in fn):
            mz = True
    return True, d, ('RPGMakerMZ' if mz else 'RPGMakerMV')


# ---------------------------------------------------------------------------
# 结构化提取（首选）：直接读 JSON，按数据库字段定位
# ---------------------------------------------------------------------------
def _walk_strings(obj, path, out, budget=None):
    """深度遍历 JSON，把 (json路径, 字符串) 记进 out。"""
    if budget is not None and budget[0] <= 0:
        return
    if isinstance(obj, str):
        if budget is not None:
            budget[0] -= 1
        out.append((path, obj))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            _walk_strings(v, '%s-%d' % (path, i), out, budget)
    elif isinstance(obj, dict):
        for k, v in obj.items():
            _walk_strings(v, '%s.%s' % (path, k), out, budget)


def _looks_like_text(s):
    """是否像玩家可见文本。"""
    if not s:
        return False
    t = s.strip()
    if len(t) < 2 or len(t) > 800:
        return False
    if _CTRL_RE.search(t):
        return False
    if _COLOR_CODE_RE.match(t):
        return False
    if _NUMERIC_RE.match(t):
        return False
    if not any(c.isalpha() for c in t):
        return False
    return True


def _is_dev_noise(t):
    """开发者注释 / 内部命令 / 资源名—— 不是玩家看到的文本。

    v3.27 实测依据：69,471 条全量遍历里，这类占了绝大多数。
    **刻意保留**：
      - 'Talk' / 'Check Crops' / 'Cum'          —— 事件指令的**指令名**，玩家在指令
                                                  菜单里能看见（编辑器），但游戏里不显示。
                                                  实测这三个都很短且是英文单词 → 保留。
      - 'AnimatedPicture 7 Speed 8'             —— 含数字+单位，内部命令 → 拦
    """
    if not t:
        return True
    # 全角尖括号包裹的开发者注释：'** SET CLAW POSITION **' / '<fog effect>'
    if _NOTE_WRAP_RE.match(t):
        return True
    # 资源名：HC_Zombies2B / HC_Actors / Spriteset2
    if _SNAKE_UPPER_RE.match(t):
        return True
    # 音效/贴图名：Thunder5 / Sword3
    if _CAMEL_NUM_RE.match(t):
        return True
    # 全大写命令：SET CLAW POSITION / ANIMATION X
    if len(t) >= 3 and _ALL_CAPS_RE.match(t) and ' ' in t:
        return True
    #变量名 / 图集名（无空格单个标识符）
    #   ⚠️ **不能只看「无空格单标识符」** —— 实测会连`Claw`（武器名）/
    #   `Player`（角色名）/`Meredith`（人物名）一起误杀，这些是**要翻译的**。
    #   真正的图集/变量名形态：**含下划线** 或 **全小写长串** 或 **camelCase**。
    if _VARNAME_RE.match(t):
        if '_' in t or _CAMEL_RE.match(t):
            return True# HC_Zombies2B / Spriteset2 / myVariable
        # 纯小写且长度 >= 6 → 多半是内部标识符（但 'Bells'/'Wing' 可能是道具名）
        if t.islower() and len(t) >= 6:
            return True
        # 其余（首字母大写的短词）**放行** —— 大概率是玩家可见名称
        return False
    # ---- JS 代码 / 插件脚本调用（v3.27 第二轮实测追加）----
    if _JS_VAR_RE.match(t):                       # $gameSelfSwitches.setValue(...)
        return True
    if _JS_CALL_RE.search(t):                     # Galv.PROJ.dir(...)
        return True
    if _JS_KEYWORD_RE.search(t):                  # if / return / function ...
        return True
    if t.rstrip().endswith((';', '{', '}', ');')):  # 语句收尾
        return True
    # 图集/贴图名：'1MC1' / '7HP_10' / '3MeredithShop1x[4x4]'
    # 判据：无空格 + 含数字 + 无标点。玩家可见文本几乎总是有空格或标点。
    if ' ' not in t and _SPRITE_NUM_RE.match(t):
        return True
    # 音效文件名：'city.' / 'door.'（带结尾句点的小写单词）
    if _SFX_DOT_RE.match(t):
        return True
    # 含空格但每段都是「标识符+数字」形态：AnimatedPicture 7 Speed 8
    parts = t.split()
    if len(parts) >= 3 and sum(1 for p in parts if p.isdigit()) >= len(parts) / 2.0:
        return True
    return False


def extract(game_dir):
    """结构化提取。返回 (rows, info)。

    rows = [(key, source), ...]，info = {'data_dir':..., 'engine':..., 'stats':{...}}
    """
    ok, data_dir, engine = detect(game_dir)
    if not ok:
        return [], {'data_dir': None, 'engine': None, 'stats': {}}

    rows = []
    stats = {}
    files = []
    for name in _DB_FILES:
        p = os.path.join(data_dir, name)
        if os.path.isfile(p):
            files.append(name)
    # Map*.json（文本量主体）
    try:
        for name in sorted(os.listdir(data_dir)):
            if _MAP_RE.match(name) and name not in files:
                files.append(name)
    except Exception:
        pass

    for name in files:
        p = os.path.join(data_dir, name)
        try:
            with open(p, 'rb') as fh:
                obj = json.loads(fh.read().decode('utf-8'))
        except Exception:
            stats[name] = -1          # 解析失败
            continue
        got = []
        _walk_strings(obj, name[:-5], got)
        n = 0
        seen = set()
        for path, s in got:
            t = s.strip()
            if not _looks_like_text(t) or _is_dev_noise(t):
                continue
            # 去重：同一文件里相同原文只取一次（RPG Maker 大量重复文本）
            key = '%s#%s' % (name, path)
            if key in seen:
                continue
            seen.add(key)
            rows.append((key, t))
            n += 1
        stats[name] = n

    return rows, {'data_dir': data_dir, 'engine': engine, 'stats': stats}


# ---------------------------------------------------------------------------
# 通用兜底：模块不可用或结构化提取失败时，至少别返回 0 条
# ---------------------------------------------------------------------------
_JSON_EVENT_RE = re.compile(
    r'"(?:code|parameters|list|name|description|text|message|choice)"\s*:')
_PUNCT_TAIL_RE = re.compile(r'[.!?"\')\]]\s*$')


def _generic_walk(obj, path, out):
    """按 JSON 里常见的文本承载字段名提取（事件指令/数据库对象）。"""
    if isinstance(obj, str):
        t = obj.strip()
        if _looks_like_text(t) and not _is_dev_noise(t):
            out.append((path, t))
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            _generic_walk(v, '%s-%d' % (path, i), out)
    elif isinstance(obj, dict):
        for k, v in obj.items():
            # 命中已知文本字段名 → 只取字符串，不下钻（避免把图片名也捞进来）
            if isinstance(v, str) and k in (
                    'text', 'message', 'name', 'description', 'choice',
                    'speaker', 'title'):
                t = v.strip()
                if _looks_like_text(t) and not _is_dev_noise(t):
                    out.append(('%s.%s' % (path, k), t))
            else:
                _generic_walk(v, '%s.%s' % (path, k), out)


def extract_generic(game_dir):
    """兜底提取：遍历所有 .json，挑出「像自然语句」的字符串。

    比结构化提取宽松—— 宁可多收噪声，也不要让用户看到「扫描到 0 条」。
    额外过滤：只保留**含空格**且**像句子**的字符串（降低 JSON 键名/枚举噪声）。
    """
    ok, data_dir, _ = detect(game_dir)
    if not ok:
        return [], {'data_dir': None, 'stats': {}}
    rows = []
    stats = {}
    try:
        names = sorted(os.listdir(data_dir))
    except Exception:
        return [], {'data_dir': data_dir, 'stats': {}}
    for name in names:
        if not name.endswith('.json'):
            continue
        p = os.path.join(data_dir, name)
        try:
            if os.path.getsize(p) > 60 * 1024 * 1024:
                stats[name] = -2# 过大，跳过
                continue
            with open(p, 'rb') as fh:
                obj = json.loads(fh.read().decode('utf-8'))
        except Exception:
            stats[name] = -1
            continue
        got = []
        _generic_walk(obj, name[:-5], got)
        n = 0
        seen = set()
        for path, s in got:
            if s in seen:
                continue
            # 只要「像句子」的：含空格 + 至少 3 词 + 长度 >= 8
            # 放过 UI 短标签（Claw / Sword）—— 那些由结构化提取负责
            if len(s) >= 8 and ' ' in s and len(s.split()) >= 3:
                seen.add(s)
                rows.append(('%s#%s' % (name, path), s))
                n += 1
        stats[name] = n
    return rows, {'data_dir': data_dir, 'stats': stats}


# ===========================================================================
# v3.29：译文回写（apply）—— 老板 2026-10-08 授权
# ===========================================================================
# 为什么必须白名单：data/*.json 里混着大量**不能翻的东西**——
#   characterName / faceName / battlerName  → 图集文件名，翻了游戏直接崩
#   switches / variables                    → 插件按名字查找，翻了脚本失效
#   code 355/655 Script                     → JS 代码
#   事件注释 108                             → 开发者注释
# 所以回写走「字段白名单 + 事件命令码白名单」，而不是全量字符串替换。

# 数据库文件 → 可翻译字段名
_DB_TEXT_FIELDS = {
    'Actors': ('name', 'nickname', 'profile'),
    'Classes': ('name',),
    'Skills': ('name', 'description', 'message1', 'message2'),
    'Items': ('name', 'description'),
    'Weapons': ('name', 'description'),
    'Armors': ('name', 'description'),
    'Enemies': ('name',),
    'States': ('name', 'message1', 'message2', 'message3', 'message4'),
    'Tilesets': (),          # 编辑器专用，游戏里不显示
    'Animations': (),        # 同上
}

# 事件命令码 → 承载文本的参数下标
#   401 = 显示文本的一行    parameters[0]
#   405 = 滚动文本的一行    parameters[0]
#   402 = 选项分支的标签    parameters[1]
#   102 = 显示选项          parameters[0] 是 [str, ...]
_EVENT_TEXT_CODES = {401: (0,), 405: (0,), 402: (1,)}
_EVENT_LIST_CODE = 102

# System.json 里可翻译的顶层字段
_SYSTEM_TEXT_KEYS = ('gameTitle', 'currencyUnit')
_SYSTEM_LIST_KEYS = ('elements', 'equipTypes', 'skillTypes', 'weaponTypes',
                     'armorTypes')
# System 里**不翻**的顶层字段：switches / variables（插件按名查找）
# 可与玩家可见文本同名，翻了会静默破坏脚本条件。
_SYSTEM_SKIP_KEYS = ('switches', 'variables', 'sounds', 'battleBgm', 'titleBgm')


def _lookup(trs, s):
    """查译文字典。命中返回新串，未命中返回 None。

    兼容提取侧的 `strip()`：json 里的值可能带前后空白，
    替换时**保留**原来的空白，只换中间的文本。
    """
    if not isinstance(s, str) or not s:
        return None
    v = trs.get(s)
    if v:
        return v
    t = s.strip()
    if t and t in trs:
        return s.replace(t, trs[t])
    return None


def _tr_str(trs, container, key, stat, miss):
    """原地替换 dict 里的一个字符串字段。命中则 stat['applied'] += 1。"""
    old = container.get(key)
    if not isinstance(old, str) or not old:
        return False
    new = _lookup(trs, old)
    if new is None or new == old:
        if old.strip() and old.strip() not in trs:
            miss.add(old.strip())
        return False
    container[key] = new
    stat['applied'] += 1
    return True


def _tr_event_list(trs, lst, stat, miss):
    """替换事件指令序列里的文本。就地修改。"""
    if not isinstance(lst, list):
        return
    for cmd in lst:
        if not isinstance(cmd, dict):
            continue
        code = cmd.get('code')
        params = cmd.get('parameters')
        if code == _EVENT_LIST_CODE and isinstance(params, list) and params:
            choices = params[0]
            if isinstance(choices, list):
                for i, c in enumerate(choices):
                    if isinstance(c, str):
                        n = _lookup(trs, c)
                        if n is not None and n != c:
                            choices[i] = n
                            stat['applied'] += 1
                        elif c.strip() and c.strip() not in trs:
                            miss.add(c.strip())
            continue
        idxs = _EVENT_TEXT_CODES.get(code)
        if not idxs or not isinstance(params, list):
            continue
        for i in idxs:
            if i < len(params) and isinstance(params[i], str):
                n = _lookup(trs, params[i])
                if n is not None and n != params[i]:
                    params[i] = n
                    stat['applied'] += 1
                elif params[i].strip() and params[i].strip() not in trs:
                    miss.add(params[i].strip())


def _apply_db_file(trs, name, obj, stat, miss, include_note):
    """数据库类 json（数组，首元素常为 null）。就地修改。"""
    base = name[:-5]
    fields = _DB_TEXT_FIELDS.get(base)
    if fields is None:
        return False
    if include_note:
        fields = tuple(fields) + ('note',)
    changed = False
    if not isinstance(obj, list):
        return False
    for item in obj:
        if not isinstance(item, dict):
            continue
        for f in fields:
            if f in item:
                if _tr_str(trs, item, f, stat, miss):
                    changed = True
    return changed


def _apply_map_file(trs, obj, stat, miss):
    """Map*.json：只翻 events[].pages[].list 里的文本行。"""
    changed = False
    events = obj.get('events') if isinstance(obj, dict) else None
    if not isinstance(events, list):
        return False
    for ev in events:
        if not isinstance(ev, dict):
            continue
        for page in ev.get('pages') or []:
            if not isinstance(page, dict):
                continue
            _tr_event_list(trs, page.get('list'), stat, miss)
            changed = True      # 是否真的改了由 applied 计数体现
    return changed


def _apply_system_file(trs, obj, stat, miss):
    """System.json：术语/菜单/类型名。switches/variables 一律跳过。"""
    if not isinstance(obj, dict):
        return False
    changed = False
    for k in _SYSTEM_TEXT_KEYS:
        if k in obj:
            if _tr_str(trs, obj, k, stat, miss):
                changed = True
    for k in _SYSTEM_LIST_KEYS:
        arr = obj.get(k)
        if isinstance(arr, list):
            for i, v in enumerate(arr):
                if isinstance(v, str):
                    n = _lookup(trs, v)
                    if n is not None and n != v:
                        arr[i] = n
                        stat['applied'] += 1
                        changed = True
                    elif v.strip() and v.strip() not in trs:
                        miss.add(v.strip())
    terms = obj.get('terms')
    if isinstance(terms, dict):
        for _tk, tv in terms.items():
            if isinstance(tv, list):
                for i, v in enumerate(tv):
                    if isinstance(v, str):
                        n = _lookup(trs, v)
                        if n is not None and n != v:
                            tv[i] = n
                            stat['applied'] += 1
                            changed = True
                        elif v.strip() and v.strip() not in trs:
                            miss.add(v.strip())
            elif isinstance(tv, dict):
                for k2, v2 in tv.items():
                    if isinstance(v2, str):
                        n = _lookup(trs, v2)
                        if n is not None and n != v2:
                            tv[k2] = n
                            stat['applied'] += 1
                            changed = True
                        elif v2.strip() and v2.strip() not in trs:
                            miss.add(v2.strip())
    return changed


def game_root(data_dir):
    """由 data 目录推回游戏根目录。

    MV 是 `<root>/www/data`（上两级），MZ 是 `<root>/data`（上一级）——
    ⚠️ 一律上两级会把 MZ 的备份写到游戏目录**外面**去，必须按布局判断。
    """
    parent = os.path.dirname(os.path.abspath(data_dir))
    if os.path.basename(parent).lower() == 'www':
        return os.path.dirname(parent)
    return parent


def backup(data_dir, backup_root):
    """全量备份 data 目录到 `<backup_root>/data-<时间戳>/`。返回备份路径。

    ⚠️ 回写**前必做**。这是老板授权 apply 的前提条件。
    """
    if not os.path.isdir(data_dir):
        raise ValueError('data 目录不存在: %s' % data_dir)
    os.makedirs(backup_root, exist_ok=True)
    stamp = time.strftime('%Y%m%d-%H%M%S')
    dst = os.path.join(backup_root, 'data-%s' % stamp)
    n = 0
    while os.path.exists(dst):
        n += 1
        dst = os.path.join(backup_root, 'data-%s-%d' % (stamp, n))
    shutil.copytree(data_dir, dst)
    return dst


def list_backups(backup_root):
    """列出可用备份点，新的在前。"""
    if not os.path.isdir(backup_root):
        return []
    out = []
    for name in os.listdir(backup_root):
        p = os.path.join(backup_root, name)
        if os.path.isdir(p) and name.startswith('data-'):
            out.append((name, p))
    out.sort(reverse=True)
    return out


def restore(backup_dir, data_dir):
    """把备份还原回 data 目录（先清空再整体拷回）。返回还原文件数。"""
    if not os.path.isdir(backup_dir):
        raise ValueError('备份目录不存在: %s' % backup_dir)
    if not os.path.isdir(data_dir):
        raise ValueError('data 目录不存在: %s' % data_dir)
    # 只覆盖备份里存在的文件，保留 data 里新增的文件
    n = 0
    for root, _dirs, files in os.walk(backup_dir):
        rel = os.path.relpath(root, backup_dir)
        dst_dir = data_dir if rel == '.' else os.path.join(data_dir, rel)
        os.makedirs(dst_dir, exist_ok=True)
        for f in files:
            shutil.copy2(os.path.join(root, f), os.path.join(dst_dir, f))
            n += 1
    return n


def apply(game_dir, translations, backup_root=None, include_note=False,
          make_backup=True):
    """把 `{原文: 译文}` 回写进 www/data/*.json。

    返回 dict：
      ok / engine / data_dir / backup / stats{files,changed_files,applied,miss}
      / miss_sample（前 20 条未命中原文）

    ⚠️ 会修改游戏本体数据 —— 调用前必须已取得用户许可，且 `make_backup=True`
       时会先全量备份。
    """
    ok, data_dir, engine = detect(game_dir)
    if not ok:
        return {'ok': False, 'reason': '不是 RPG Maker MV/MZ 工程'}
    trs = {}
    for k, v in (translations or {}).items():
        if isinstance(k, str) and k and isinstance(v, str) and v:
            trs[k] = v
    if not trs:
        return {'ok': False, 'reason': '译文为空'}

    bk = None
    if make_backup:
        if backup_root is None:
            backup_root = os.path.join(game_root(data_dir), '_原文备份')
        bk = backup(data_dir, backup_root)

    stat = {'files': 0, 'changed_files': 0, 'applied': 0}
    miss = set()
    try:
        names = sorted(os.listdir(data_dir))
    except Exception:
        return {'ok': False, 'reason': '无法列出 data 目录', 'backup': bk}

    for name in names:
        if not name.lower().endswith('.json'):
            continue
        p = os.path.join(data_dir, name)
        try:
            with open(p, 'rb') as fh:
                raw = fh.read()
            obj = json.loads(raw.decode('utf-8-sig'))
        except Exception:
            continue
        stat['files'] += 1
        before = stat['applied']
        changed = False
        if name == 'System.json':
            changed = _apply_system_file(trs, obj, stat, miss)
        elif name == 'CommonEvents.json':
            if isinstance(obj, list):
                for item in obj:
                    if isinstance(item, dict):
                        _tr_event_list(trs, item.get('list'), stat, miss)
                changed = True
        elif name == 'Troops.json':
            if isinstance(obj, list):
                for item in obj:
                    if not isinstance(item, dict):
                        continue
                    for page in item.get('pages') or []:
                        if isinstance(page, dict):
                            _tr_event_list(trs, page.get('list'), stat, miss)
                changed = True
        elif name == 'MapInfos.json':
            if isinstance(obj, list):
                for item in obj:
                    if isinstance(item, dict) and 'name' in item:
                        _tr_str(trs, item, 'name', stat, miss)
                changed = True
        elif _MAP_RE.match(name):
            changed = _apply_map_file(trs, obj, stat, miss)
        else:
            changed = _apply_db_file(trs, name, obj, stat, miss, include_note)

        if changed and stat['applied'] > before:
            stat['changed_files'] += 1
            tmp = p + '.tmp_apply'
            with open(tmp, 'w', encoding='utf-8', newline='') as fh:
                json.dump(obj, fh, ensure_ascii=False, separators=(',', ':'))
            os.replace(tmp, p)
        elif changed:
            # 结构变了但没命中任何译文 → 不落盘，避免无意义改动
            pass

    return {
        'ok': True,
        'engine': engine,
        'data_dir': data_dir,
        'backup': bk,
        'stats': dict(stat, miss=len(miss)),
        'miss_sample': sorted(miss)[:20],
    }