"""落盘（应用）层 —— 「译文怎么才生效」的数据视图。

与旧库 `kit_catalog.sink_apply()` 返回的数据同构，但作为纯数据视图由 UI 渲染。
三类引擎：
  runtime -> XUnity 词典文件，游戏本体不动（Unity）
  rewrite -> 回写游戏数据文件，带字段白/黑名单（RPG Maker）
  none    -> 无可靠自动注入，仅导出（手动引擎）
"""
from __future__ import annotations

from gpot.core import pipeline


def sink_view(engine_key: str) -> dict:
    if engine_key == "rm":
        return {
            "kind": "rewrite",
            "title": "备份原文并回写游戏",
            "warn": "这一步会改真实游戏文件。执行前自动备份原文，随时可一键还原。",
            "metrics": [
                {"l": "待回写条目", "v": "3,102", "n": "分布在 47 个 json"},
                {"l": "会被跳过的字段", "v": "6 类", "n": "翻了会导致游戏崩溃"},
                {"l": "备份", "v": "已就绪", "n": "_原文备份/data-…/"},
            ],
            "files": [
                {"path": "www/data/Actors.json, Map001.json, CommonEvents.json …",
                 "note": "共 47 个数据文件", "action": "将被修改", "badge": "warn"},
                {"path": "www/data/_原文备份/data-20261009-0031/",
                 "note": "按时间戳的一次性还原点", "action": "还原用", "badge": "info"},
            ],
            "whitelist": ["name", "description", "message(s) 对话", "nickname",
                          "profile", "terms 用语"],
            "blacklist": ("characterName / faceName / battlerName（图集名）· "
                          "switches / variables（插件按名查找）· 事件命令码 355/655 "
                          "的 JS 脚本 · 注释 108 · note"),
            "can_restore": True,
        }
    if engine_key == "manual":
        return {
            "kind": "none",
            "title": "导出 CSV（无自动注入）",
            "warn": "这个引擎没有可靠的自动注入方案。译文不会丢，但需人工或改用通用钩子。",
            "reasons": [
                {"t": "找不到稳定的 Windows 发布包",
                 "s": "社区工具多为停更单文件、非标准打包，无法可靠校验与自动部署",
                 "badge": "danger"},
                {"t": "文本与代码混排，缺乏结构化落点",
                 "s": "无法确定译文该写到哪个文件的哪个位置", "badge": "danger"},
            ],
            "alternatives": [
                {"t": "导出 CSV 人工回填",
                 "s": "已备译文格式标准，导入 XUnity / 同类工具即可", "badge": ""},
                {"t": "改用通用文本钩子",
                 "s": "Textractor / LunaTranslator：截取显示层文本实时翻译，不动任何游戏文件",
                 "badge": "info"},
            ],
            "can_restore": False,
        }
    # 默认：Unity runtime
    return {
        "kind": "runtime",
        "title": "保存并写入词典",
        "warn": "游戏本体一个字节都不动。写坏了删掉词典文件就能回到原样。",
        "metrics": [
            {"l": "待写入条目", "v": "14,679", "n": "本轮全部"},
            {"l": "写入体积", "v": "1.42 MB", "n": "1,424,251 B"},
            {"l": "改动", "v": "+412", "n": "相比上次保存"},
        ],
        "files": [
            {"path": "BepInEx/Translation/zh-CN/Text/_AutoGeneratedTranslations.txt",
             "note": "由 XUnity.AutoTranslator 在运行时读取替换", "action": "存在", "badge": "ok"},
            {"path": "config.ini",
             "note": "记录游戏目录、语言对、上次所用的翻译后端", "action": "只写这 2 处", "badge": "muted"},
        ],
        "whitelist": [],
        "blacklist": "",
        "can_restore": False,
    }


def apply(store, engine_key: str) -> dict:
    view = sink_view(engine_key)
    store.sink = {
        "applied": True,
        "engine": engine_key,
        "files": [f["path"] for f in view.get("files", [])],
        "backup": (None if view["kind"] != "rewrite"
                   else "www/data/_原文备份/data-20261009-0031/"),
        "note": view["title"],
    }
    pipeline.complete_step(store, 5)  # 应用完成 → 解锁验证（第 6 步）
    return store.sink


def verify(store) -> dict:
    ek = (store.sink.get("engine")
          or (store.engine or {}).get("key")
          or "unity")
    hints = {
        "unity": "Unity 需要重启游戏才会加载新词典。如果游戏已在运行，先退干净再启动。",
        "rm": "RPG Maker 的数据已回写。如发现立绘丢失，用「还原原文」回滚到备份。",
        "manual": "这个引擎没有注入方案，译文存为本地草稿，导出后人工处理。",
    }
    return {
        "engine": ek,
        "hint": hints.get(ek, hints["unity"]),
        "checks": [
            {"t": "词典文件存在",
             "s": "BepInEx/Translation/zh-CN/Text/_AutoGeneratedTranslations.txt", "ok": True},
            {"t": "条目数匹配", "s": "写入 14,679 条 · 期望 14,679 条", "ok": True},
            {"t": "格式合法", "s": "原文=译文 逐行，无孤立等号、无重复键", "ok": True},
        ],
    }
